### ISSUE TITLE
Directory remove/rename issue

### ISSUE THREAD

**Issue by Woit** [wojciech-kulik/xcodebuild.nvim#114]
Hey!

All methods from `xcodebuild.project.manager` works good, except directory moving/renaming. Each time when i try to call `delete_group` or `move_or_rename_group` i getting some warnings like:
```
Renamed "TestFolder" successfully
Could not find "TestFolder" in project
```
and changes not reflected in xcode project

**Comment by wojciech-kulik** [comment]
Hi! What is the structure of your project? Single module/multiple modules/SPM modules?

Does it also happen if you use Project Manager or integration with nvim-tree/oil.nvim?

**Comment by Woit** [comment]
Single .xcodeproj, with SPM. Im not using nvim-tree/oil, so i can't check that.
Are you using xcodegen behind? Because it looks like deletion process falling on last step, when we needs to re-generate .xcodeproj. Because directory delete is fine (i mean it deletes from filesystem)

**Comment by wojciech-kulik** [comment]
It is using Xcodeproj (ruby tool) underneath. If you use the function that you mentioned, they don't perform any disk operations, so I guess it's something else?

**Comment by wojciech-kulik** [comment]
Could you try performing these operations using built-in interface? Call `:XcodebuildProjectManager`

**Comment by Woit** [comment]
If i navigate to inside target folder and then do `:XcodebuildProjectManager -> Delete current group` then it works

**Comment by wojciech-kulik** [comment]
That's interesting, because in my integrations with nvim-tree and oil.nvim I also react on AFTER events and it works well. If you physically delete files/folders it shouldn't have any effect on your `xcodeproj` therefore the tool should be also able to perform actions and update xcodeproj.

Could you show your code? Is it the one from the other issue?

**Comment by wojciech-kulik** [comment]
And just one thought. Maybe you are subscribing twice for events? And the second call fails. Actually your output confirms that, because you've got 2 messages. I think there should be only one.

**Comment by Woit** [comment]
> Could you show your code? Is it the one from the other issue?
yep

**Comment by wojciech-kulik** [comment]
Yeap, I have just found the issues.

As you said, it happens after the file is deleted so you can't rely on `vim.fn.isdirectory` because it check physical files. So the solution is:

```lua
    api.subscribe({
      event = "file_deleted",
      handler = function(path)
        local extension = vim.fn.fnamemodify(path, ":e")
        local isDir = extension == ""
        if isDir then
          if shouldUpdateProject(path) then
            projectManager.delete_group(path)
          end
        else
          if shouldUpdateProject(path) then
            projectManager.delete_file(path)
          end
        end
      end,
    })
```

With rename/move you just need to check the final path, not the source (which doesn't exist anymore):

```lua
local isDir = vim.fn.isdirectory(paths.destination) == 1
```

It should solve your problem. Let me know if it works.

**Comment by Woit** [comment]
All working as expected, thanks!
