### ISSUE TITLE
Support searching in project files and swift packages.

### ISSUE THREAD

**Issue by leo1mml** [wojciech-kulik/xcodebuild.nvim#172]
First of all this is an awesome plugin. 

Second: Is it possible to search for files/text inside the sub swift packages? It would be great to have a seamless integrated code navigation in neovim.
I wonder if there's any peculiarity with local packages and remote ones inside derived data.
I have no experience with making neovim plugins, so I'm unable to help. But I believe this feature would be great for people using this plug in.

**Comment by wojciech-kulik** [comment]
Hi and thank you!

Could you provide more detail on what do you mean by "sub swift packages"? What's your project structure? Do you have xcodeproj and you add SPM packages as dependencies? Are they local or remote?

I've got the project modularized with SPM and it's possible to navigate between packages. I'm also able to navigate to external package - but it depends on how it's created, some packages may include xcframework instead of source code

**Comment by leo1mml** [comment]
Hi @wojciech-kulik sorry for the long time to respond. Currently it is possible to navigate to packages inside the project if you go to definition or find references.
What I mean was to have something more similar to what we have in Xcode when we search for something **In Project** and **Package Dependencies**. This way when we look for code we're looking at the whole picture and  not just the project scope. The packages are in the derived data stuff, so maybe adding their folders to the fuzzy finder would solve the problem.

**Comment by wojciech-kulik** [comment]
LSP features are implemented in sourcekit-lsp, the plugin itself doesn't do anything in this area. I don't think there is any option to modify that behavior.

If you are just looking for a better text search, you could probably configure Telescope to search in a specific directory instead of the whole `cwd`.

**Comment by leo1mml** [comment]
That would work. But I think it would be a good experience if xcodebuild could already link the folders added as dependencies, either being in the derived data (remote packages) or custom directories(local packages).
Or maybe xcodebuild could also have some way to list these directories for easier navigation, similar to what xcode does for us to see the code in the file tree explorer.
That's just an idea though. Thanks for hearing me out.

**Comment by wojciech-kulik** [comment]
That would be quite a challenging change. To make it usable it would require reinventing a file tree plugin from scratch.

Why do you need it? If you have to check an implementation, you can quickly jump to it using LSP. If you heavily browse those packages you can always navigate to the root of all packages and open another Neovim instance.

If I were you, I would try solving this problem using existing plugins like nvim-tree, noe-tree, or something similar. Maybe you could try playing with symlinks/hard links/plugin config to make packages appear in your file tree. Basically, all packages that are used are in: `~/Library/Developer/Xcode/DerivedData/<project>/SourcePackages/checkouts`.

At this point, I don't see how we could easily integrate it unless you've got some ideas.
