### ISSUE TITLE
How to remove all the cache to make sourcekit-lsp work again?

### ISSUE THREAD

**Issue by Fr3027** [wojciech-kulik/xcodebuild.nvim#267]
Thank you for that awesome work🌈!, which allows me to write SwiftUI code on Neovim. 
However, I've encountered a significant issue hope you can guide me.

Here's the situation: today, when I opened the project in Neovim, I received a "no such module" error, and the "go to definition" feature stopped working. I switched to Xcode, ran a clean build, and restarted Neovim, but the issue persisted. It's quite puzzling and I can't figure it out. Notably, the hover feature is working.

I then copied the original project and renamed it to TestApp, and performed the following steps:

```bash
1.cd path_of_test_app
2.xcodegen
3.Opened it with Xcode and performed a clean build
4.xcode-build-server config -scheme TestApp -project TestApp.xcodeproj
5.Opened the project directory in Neovim
```
Both "go to definition" and "import package" worked fine again.

However, the same operations in the old project directory still yield the same issues.
Could you please guide me through this? Maybe a kind of cache things?

**Comment by wojciech-kulik** [comment]
Hard to say, usually clean build using Xcode should help. Make sure that your paths are correct i.e. your lsp points to a client that belongs to Xcode that is configured for cmd line (if you use multiple instances). 

You can also check out my sample config for ios development and see if it works with it.

You can also run `checkhealth xcodebuild` to run some diagnostics

**Comment by wojciech-kulik** [comment]
Also make sure that your lsp config points to sourcekit-lsp bundled with Xcode, not the global one from /usr/bin

**Comment by Fr3027** [comment]
Thank you for the quick response, I change from auto parsing to use manual parsing, now it is working again! Here is the code :
```bash
function M.build_project(opts)
    local bundle_dir = opts.workingDirectory.."/.bundle"
    local command0 = "rm -rf " .. bundle_dir .. "*" -- For Unix-based systems (Linux, macOS)
    os.execute(command0)

    local command = {
        "xcodebuild",
        opts.clean and "clean" or nil,
        opts.buildForTesting and "build-for-testing" or "build",
        get_project_param(opts.projectFile),
        opts.projectFile,
        "-scheme",
        opts.scheme,
        "-destination",
        "id=" .. opts.destination,
        "-resultBundlePath",
        bundle_dir,
    }

    command = util.merge_array(command, opts.extraBuildArgs)
    command = util.skip_nil(command)
    command = xcodebuildOffline.wrap_command_if_needed(command)

    -- Create a shell command that includes the pipe
    local shell_command = table.concat(command, " ") .. "| tee build.log; xcode-build-server parse" .. (opts.clean and "" or " -a") .. " build.log >/dev/null 2>&1"

```

**Comment by FelixLisczyk** [comment]
Apologies for commenting on a closed issue. Please let me know if I should open a new one.

I experienced a similar problem with some of my **macOS** projects when I opened and configured them for the first time in Neovim. I think the issue is that [xcode-build-server](https://github.com/SolaWing/xcode-build-server) requires a result bundle to parse the symbols. This result bundle is only generated if `xcodebuild` gets called with the `-resultBundlePath` parameter. From what I can see, `xcodebuild.nvim` does not currently use this parameter.

I managed to get the LSP to function in my projects by deleting the derived data folder and running `xcodebuild` manually with the required parameters. For example: `xcodebuild ... -resultBundlePath <path-to-derived-data>/resultBundle.xcresult`.

You can verify if `xcode-build-server` has the required information by checking its cache directory at `~/Library/Caches/xcode-build-server/`. If the project folder doesn't contain a `compile_file`, or if this file only has an empty array, the LSP will not work.

The [SweetPad extension](https://github.com/sweetpad-dev/sweetpad) for VS Code [also uses the -resultBundlePath parameter](https://github.com/sweetpad-dev/sweetpad/blob/68e5dbbf6ac5c69e2d798acc821a30ef08ebf184/src/build/commands.ts#L485).

**Comment by wojciech-kulik** [comment]
Interesting case, please open a new issue, I'll try to investigate it. If you wish you can also try contributing and research this problem.

**Comment by FelixLisczyk** [comment]
I've replicated the issue with a sample project and created issue #281. Thank you for looking into it and for developing such an excellent plugin! 😊
