### ISSUE TITLE
Never-completing builds in certain situations

### ISSUE THREAD

**Issue by PangMo5** [wojciech-kulik/xcodebuild.nvim#45]
This is the issue mentioned in https://github.com/wojciech-kulik/xcodebuild.nvim/discussions/44#discussioncomment-8540610

First of all, my environment is using [neovide ](https://neovide.dev/) and [dashboard.nvim](https://github.com/nvimdev/dashboard-nvim).

If I open and build the project inside the shell using `nvim` or `neovide` commands from the root of project, it works fine. 

But Run `neovide` and open the that project in the `recently projects` section of `dashboard.nvim`,
When I try to build it, the build never finishes and continues.

Even when using the `nvim` command in the shell, running neovim with commands like `nvim {project root}` on the parent root of the project causes problems.

Just in case, I created a new iOS sample project and tried the same thing, but the problem was the same.

The output of `:lua print(vi.fn.getcwd())` in all situations is the same.

#### When running as a shell command from the project root
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/16532526/71f0d7dc-9ac0-4096-ae83-1f2d934d3493)

#### When running as Dashboard.nvim, etc.
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/16532526/43724243-8acb-4f94-aa1f-55ad9e4366ba)

**Comment by wojciech-kulik** [comment]
I investigated the problem and it's caused most likely because of switching between projects via Dashboard. In general, the plugin doesn't support switching projects. However, there is some workaround for it, you can check this thread:  #7.

Here is a sample config for Dashboard that reloads the plugin:
```
return {
  "nvimdev/dashboard-nvim",
  event = "VimEnter",
  dependencies = { { "nvim-tree/nvim-web-devicons" } },
  config = function()
    require("dashboard").setup({
      config = {
        project = {
          action = function(path)
            vim.cmd("Telescope find_files cwd=" .. path)

            for name, _ in pairs(package.loaded) do
              if string.find(name, "xcodebuild%.") then
                package.loaded[name] = nil
              end
            end

            require("xcodebuild").setup({
              -- your options
            })
            require("xcodebuild.project.appdata").load_last_report()
          end,
        },
      },
    })
  end,
}
```

Please check it out and let me know. If you still encounter issues, please check out what shows the command `:XcodebuildShowConfig` make sure that the project is correctly set up. If you messed with the previous version without reloading the plugin it could break your project config, so setup it up again if necessary.

**Comment by PangMo5** [comment]
Thanks!

I reloaded the plugin as you suggested and it works fine.

I'm using Lazy.nvim, so `Lazy reload xcodebuild.nvim` also seems to work.

Thanks again for the awesome plugin.
