### ISSUE TITLE
Traversing all directories

### ISSUE THREAD

**Issue by dtln820** [wojciech-kulik/xcodebuild.nvim#5]
Hey. First of all, thank you for this, it's amazing ❤️ I integrated your plugin into my lazyvim distro, the issue is if I run the `nvim` command in the home directory, then I guess it's trying to find workspace files recursively, and in the home folder that takes a lot of time. Is there a way to write a workaround, to control somehow if it should search/or to trigger setup manually?

I did a little debugging, so seems the function that does this is `util.lua:78 M.find_all_swift_files()`

**Comment by wojciech-kulik** [comment]
Hello, thank you for reporting this issue! 

Yes, correct, I spotted the problem, it should be fixed in a few minutes :)

**Comment by dtln820** [comment]
Also if we start the nvim in home directory, CD to our workspace and then trigger `Show Configuration Wizard` we encounter the same issue.

Thanks for the quick fix 👍

**Comment by wojciech-kulik** [comment]
Ok, I fixed the issue. I also added `commands.project_search_max_depth` config option to control search depth for xcodeproj/xcworkspace. This way the wizard should not freeze for good. 

However, please keep in mind that the plugin is not meant to be run from external folders. You should open nvim from your project root (cwd should be set there). Otherwise, if your run build/test it will anyway call `find_all_swift_files` and everything will freeze.

Also, if you are using configs from my article for `nvim-lint` and `conform.nvim` that look for `.swiftformat` and `.swiftlint.yml` files, you may want to add `-maxdepth 2` parameter to `find` command. Those commands start when nvim starts, so if your run it from home, it may take some time. Later, I will try to find a better solution, maybe we could search for config files once first Swift file is activated and not immediately after start.

**Comment by wojciech-kulik** [comment]
@dtln820 thank you for reporting this issue 💪 . Let me know if it works well now :).

**Comment by dtln820** [comment]
@wojciech-kulik Yep, tested, works great, thanks! I'm thinking if it's possible somehow to link NeoTree and this plugin, so whenever NeoTree sets a new root directory, it reloads the plugin or something (I'm new to this, so just bouncing ideas 😄)

**Comment by wojciech-kulik** [comment]
Great! 

It should be possible. Currently, the plugin relies on `vim.fn.getcwd()`. So if your NeoTree changes cwd it should work fine. Although, I haven't tested it yet :). Maybe it is already working like that, I will check it later.

**Comment by wojciech-kulik** [comment]
@dtln820 I added SwiftLint and SwiftFormat config detection when they are used for the first time + I'm caching the result to avoid calling `find` every time. If you want you can check out the configuration here: [ios-dev-starter-nvim](https://github.com/wojciech-kulik/ios-dev-starter-nvim).

Regarding switching projects, I posted a solution here: https://github.com/wojciech-kulik/xcodebuild.nvim/discussions/7

**Comment by dtln820** [comment]
@wojciech-kulik Thanks a lot. Great work 🎉
